@baseUrl = https://localhost:3000/v1/api

GET {{baseUrl}}/usuarios


###
GET {{baseUrl}}/tipodocumentos





###
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
    "codTipoDocumento": "01",
    "numDocumento": "12345678",
    "nombres": "Daniel",
    "apePaterno": "Prado",
    "apeMaterno": "Jimenez",
    "correo": "dprado@autonoma.edu.pe",
    "celular": "987654321",
    "contrasena": "Clave2026",
    "confirmarContrasena": "Clave2026",
    "aceptaTerminos": true
}
